version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: farmx-db
    restart: always
    environment:
      MYSQL_DATABASE: farmxchain_db
      MYSQL_ROOT_PASSWORD: Rathi@1805A
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: farmx-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/farmxchain_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Rathi@1805A
      - JWT_SECRET=FarmXChainSecretKeyForJWTGeneration123!
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: farmx-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
